services:
  api:
    build:
      context: ./api
    working_dir: /app  
    container_name: cloudbackup
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env   
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: clouduser
      POSTGRES_PASSWORD: cloudpass
      POSTGRES_DB: cloudbackup
    ports:
      - "5432:5432"
    volumes:
     - pgdatacloud:/var/lib/postgresql/data  

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
     - redisdatacloud:/data 
volumes:
  pgdatacloud:
  redisdatacloud:

       
